---
# tasks file for roles/resourcegroup

- name: create a web app
  azure_rm_webapp:
    name: "{{ app.name }}-{{ dict.resource_group }}"
    location: "{{ azure.location }}"
    resource_group: myResourceGroup
    name: myWinWebapp
    plan:
      resource_group: myAppServicePlan_rg
      name: myAppServicePlan
      is_linux: false
      sku: S1